name: SNS Action
description: Publish a message on an SNS topic

branding:
  icon: document
  color: gray-dark

inputs:
  topic:
    description: "Topic ARN to send message to"
    required: true
    type: string
  message:
    description: "Message to send"
    required: true
    type: string
  role:
    description: "Role ARN to assume"
    required: true
    type: string
  region:
    description: "Region to use"
    required: true
    type: string

outputs:
  messageId:
    description: "Unique identifier assigned to the published message"
    value: ${{ steps.publish.outputs.messageId }}

runs:
  using: "composite"

  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2.2.0
      with:
        role-to-assume: ${{ inputs.role }}
        aws-region: ${{ inputs.region }}

    - name: Download sns-action
      uses: robinraju/release-downloader@v1.8
      with:
        repository: "leocomelli/sns-action"
        tag: "v0.2"
        fileName: "sns-action"

    - name: Publish a message
      id: publish
      shell: bash
      run: |
        chmod +x sns-action
        ID=$(./sns-action \
          --topic "${{ inputs.topic }}" \
          --message "${{ inputs.message }}")

        echo "messageId=$ID" >> $GITHUB_OUTPUT
