name: SNS Action
description: Publish a message on an SNS topic

branding:
  icon: document
  color: gray-dark

inputs:
  topic:
    required: true
    type: string
  mesasge:
    required: true
    type: string
  role:
    required: false
    type: string

outputs:
  messageId:
    description: "Unique identifier assigned to the published message"
    value: ${{ steps.publish.outputs.messageId }}

runs:
  using: "composite"

  steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: "1.20"

    - name: Publish a message
      id: publish
      shell: bash
      run: |
        ID=$(go run ${{ github.action_path }}/main.go \
          --topic "${{ inputs.topic }}" \
          --message "${{ inputs.message }}" \
          --role "${{ inputs.role }}")

        echo "messageId=$ID" >> $GITHUB_OUTPUT
